yourdoctor/yourdoctor/yd_webapp/urls.py
from django.urls import path

from yd_webapp import views

app_name = 'yd_webapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('timetable/',views.timetable,name='timetable'),
    path('patient/',views.useraccount,name='user'),
    path('edittime/',views.edittime,name='edittime'),
    path('booking/', views.booking, name='booking'),
    path('doctor/', views.doctoraccount, name='doctor'),
    path('index/', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('doclogin/', views.doc_login, name='doclogin'),

    path('show_questions/', views.show_questions, name='show_questions'),
    path('save_answer/', views.save_answer, name='save_answer'),
    # path('sqp/', views.show_questions_patient, name='show_questions_patient'),
    # path('save_question_patient/', views.ask_question_patient, name='show_questions_patient'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback_page/', views.feedback_page, name='feedback'),
    path('message/', views.save_question_patient, name='message'),
    # path('onlinedoctor/',views.show_questions_page, name='onlinedoctor')
    path('onlinedoctor/',views.answer_question, name='onlinedoctor')


]

yourdoctor/yourdoctor/yourdoctor/urls.py
from django.contrib import admin
from django.urls import path, include

from yd_webapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('yd_webapp/', include('yd_webapp.urls')),
]

yourdoctor/yourdoctor/yd_webapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Patients(models.Model):
    patient_id = models.AutoField(primary_key=True)
    patient_name = models.CharField(max_length=50, null=True)
    patient_email = models.EmailField(null=True)
    patient_age = models.IntegerField(null=True)
    patient_gender = models.CharField(max_length=5, null=True)
    patient_phone_num = models.CharField(max_length=20, null=True)
    patient_psw = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=200, null=True)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.patient_name)
        super(Patients, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Patients'

    def __str__(self):
        return str(self.patient_id)


class Doctors(models.Model):
    doctor_id = models.AutoField(primary_key=True)
    doctor_name = models.CharField(max_length=50, null=True)
    doctor_email = models.EmailField(unique=True)
    doctor_psw = models.CharField(max_length=50)

    def __str__(self):
        return str(self.doctor_id)


class Admins(models.Model):
    admin_id = models.AutoField(primary_key=True)
    admin_email = models.EmailField(unique=True)
    admin_psw = models.CharField(max_length=50)

    def __str__(self):
        return str(self.admin_id)


# contains the doctors' available time so that the doctors can choose
# t_id: the unique id of all the available time of each doctor
# time_id: from Mon. to Fri.
class Timetable(models.Model):
    t_id = models.AutoField(primary_key=True, default=0)
    doctor_id = models.ForeignKey('Doctors', on_delete=models.CASCADE, null=True)
    time_choices = (
        (1, u'Mon.'),
        (2, u'Tue.'),
        (3, u'Wed.'),
        (4, u'Thu.'),
        (5, u'Fri.'),
    )
    time_id = models.IntegerField(choices=time_choices, null=True)
    status_choices = (
        (0, u'available'),
        (1, u'not available')
    )
    status = models.IntegerField(choices=status_choices, default=0)

    def __str__(self):
        return str(self.t_id)


# contains patients' questions and the answers from the doctor
class Record(models.Model):
    record_id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey('Patients', on_delete=models.CASCADE)
    doctor_id = models.ForeignKey('Doctors', on_delete=models.CASCADE, null=True)
    question_context = models.CharField(max_length=500, default='', null=True)
    answer_context = models.CharField(max_length=500, default='', null=True)


# contains the booking details about the patients
class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey('Patients', on_delete=models.CASCADE)
    t_id = models.ForeignKey('Timetable', null=True, on_delete=models.CASCADE)






from django.contrib import admin

admin.site.register(Patients)
admin.site.register(Doctors)
admin.site.register(Admins)

yourdoctor/yd_webapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from yd_webapp import models
from django.contrib import messages
from django.contrib.auth.backends import ModelBackend
from django.db.models.query_utils import Q
from yd_webapp import models
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
from django.forms.models import model_to_dict

# Create your views here.


# example:
def index(request):
    context_dict={}
    context_dict['boldmessage']="Hello, this is an example."
    return render(request,'yd_webapp/index.html',context=context_dict)


# to validate email address
def validate_email(email):
    from django.core.validators import validate_email
    from django.core.exceptions import ValidationError
    try:
        validate_email(email)
        return True
    except ValidationError:
        return False


# ********************************************************
# ****************function of patients *******************
# ********************************************************


# user make an appointment
def booking(request):
    if request.method == 'GET':

        print(request.session.get('user_id'))
        user = models.Patients.objects.get(patient_id=request.session.get('user_id'))
        print(user.patient_id)

        context_dict = {}
        context_dict['time_choices'] = models.Timetable.objects.filter(status=0)
        context_dict['appointment'] = models.Booking.objects.filter(patient_id=user)

        return render(request, 'yd_webapp/booking.html', context=context_dict)

    if request.method == 'POST':
        # availabletime is the t_id in the timetable which is available
        select_t_id = request.POST.get('availabletime')

        # the time record object that the patient choose
        select_time = models.Timetable.objects.get(t_id=int(select_t_id))
        patient = models.Patients.objects.get(patient_id=request.session.get('user_id'))

        # updata the timetable after booking
        models.Timetable.objects.filter(t_id=int(select_t_id)).update(status=1)
        models.Booking.objects.create(
            patient_id=patient,
            t_id=select_time,
        )
        print("Booking succeed")

        messages.success(request, 'Your book is accepted! ')
        return redirect('/yd_webapp/patient/')

    context_dict = {}
    context_dict['time_choices'] = models.Timetable.objects.filter(status=0)

    messages.success(request, "Your booking successed!")

    return render(request, 'yd_webapp/booking.html', context=context_dict)


# send messages and ask questions online
def ask_question(request):
    if request.method == 'POST':
        enter_email = request.POST.get('email')
        enter_question = request.POST.get('question')

        models.Record.objects.create(
            # this can be modified(?)
            patient_id=models.Patients.objects.get(patient_email=enter_email).patient_id,
            question_context=enter_question,
        )

    return HttpResponse("Please wait for the answer")


# show the records of the patient to give the feedback
def show_record(request):
    patient_id = ''
    records = models.Record.objects.filter(patient_id=patient_id)
    context_dict = {}
    context_dict['records'] = records
    return render(request, '', context=context_dict)


# give the feedback
def give_feedback(request):
    return render(request, '')


# ********************************************************
# ****************function of doctors *******************
# ********************************************************


# ？
def timetable(request):
    if request.method == 'GET':
        return render(request, 'yd_webapp/timetable.html')

    if request.method == 'POST':
        select_time = request.POST.get('gender')
        print(select_time)

    context_dict={}
    # context_dict['doctor']="only doctor can access this page,for edit and choose"

    return render(request,'yd_webapp/timetable.html',context=context_dict)


# get patient information
def useraccount(request):
    context_dict = {}

    if request.method == 'GET':
        return render(request, 'yd_webapp/patient.html', context=context_dict)

    if request.method == 'POST':
        user = models.Patients.objects.get(patient_id=2)

    return render(request,'yd_webapp/patient.html',context=context_dict)


# get doctor information
def doctoraccount(request):
    context_dict = {}

    if request.method == 'GET':
        return render(request, 'yd_webapp/doctor.html', context=context_dict)

    if request.method == 'POST':
        user = models.Patients.objects.get(patient_id=2)

    return render(request,'yd_webapp/doctor.html',context=context_dict)


# doctor edits timetable
def edittime(request):
    doctor_id = request.session.get('user_id')
    print("doctor_id:", doctor_id)

    if request.method == 'GET':
        context_dict = {}
        times = models.Timetable.objects.filter(doctor_id=doctor_id).filter(status=0)
        timetable = []
        for i in times:
            # print(i.time_id)
            timetable.append(i.get_time_id_display)
        context_dict['timetable'] = timetable
        return render(request, 'yd_webapp/edittime.html', context=context_dict)

    if request.method == 'POST':
        timetable = request.POST.getlist('time')
        timetable = [int(i) for i in timetable]
        print(timetable)

        for i in range(1, 6):
            if i in timetable:
                models.Timetable.objects.filter(doctor_id=doctor_id).filter(time_id=int(i)).update(status=0)
                print("updata 0")
            else:
                models.Timetable.objects.filter(doctor_id=doctor_id).filter(time_id=int(i)).update(status=1)
                print("updata 1")

    context_dict={}
    times = models.Timetable.objects.filter(doctor_id=doctor_id).filter(status=0)
    timetable = []
    for i in times:
        print(i.time_id)
        timetable.append(i.get_time_id_display)
    context_dict['timetable'] = timetable

    return render(request,'yd_webapp/edittime.html',context=context_dict)


# patients log in
def user_login(request):
    if request.method =="POST":
        enter_email = request.POST.get('email')
        enter_psw = request.POST.get('password')
        print(enter_email)
        print(enter_psw)

        try:
            user = models.Patients.objects.get(patient_email=enter_email)
            print(user)
            if enter_psw == user.patient_psw:
                request.session.set_expiry(3000)  # Session Authentication duration is 3000s. After 3000s, the session authentication becomes invalid
                # login(request,user)
                request.session['is_login'] = True
                request.session['user_id'] = user.patient_id
                request.session['user_name'] = user.patient_name
                request.session['user_gender'] = user.patient_gender
                request.session['user_age'] = user.patient_age
                request.session['user_address'] = user.address
                request.session['user_email'] = user.patient_email
                request.session['user_phone'] = user.patient_phone_num
                return redirect('yd_webapp:user')
            else:
                print("password wrong")
                return render(request,'yd_webapp/login.html', {'Error': 'Error: Please check your password!'})
        except:
            print("not exist")
            return render(request, 'yd_webapp/login.html', {'Error': 'Error: User does not exist in our system'})
    else:
        return render(request,'yd_webapp/login.html')


# doctors log in
def doc_login(request):
    if request.method =="POST":
        enter_email = request.POST.get('email')
        enter_psw = request.POST.get('password')
        print(enter_email)
        print(enter_psw)

        try:
            user = models.Doctors.objects.get(doctor_email=enter_email)
            print(user)
            if enter_psw == user.doctor_psw:
                request.session.set_expiry(3000)  # Session Authentication duration is 3000s. After 3000s, the session authentication becomes invalid
                # login(request,user)
                request.session['username'] = request.POST.get('email')
                request.session['is_login'] = True
                request.session['user_id'] = user.doctor_id
                request.session['user_name'] = user.doctor_name
                request.session['user_email'] = user.doctor_email
                return redirect('yd_webapp:doctor')
            else:
                print("password wrong")
                return render(request, 'yd_webapp/doclogin.html', {'Error': 'Error: Please check your password!'})
        except:
            print("not exist")
            return render(request, 'yd_webapp/doclogin.html', {'Error': 'Error: User does not exist in our system'})
    else:
        return render(request, 'yd_webapp/doclogin.html')


def user_logout(request):
    request.session.clear()
    print("Log out")
    return redirect('yd_webapp:index')


# submit registration information
def user_register(request):

    if request.method == 'POST':
        enter_email = request.POST.get('email')
        enter_name = request.POST.get('username')
        enter_age = request.POST.get('age')
        enter_gender = request.POST.get('gender')
        enter_phone = request.POST.get('phonenumber')
        enter_address = request.POST.get('address')
        enter_password = request.POST.get('password')
        enter_confirm_pwd = request.POST.get('confirm_pwd')

        # Determine whether any received data is empty
        if not enter_email.strip():
            error_message = "Email can not be empty"
            return render(request, 'yd_webapp/register.html', locals())
        elif not enter_name.strip():
            error_message = "Name can not be empty"

yourdoctor/templates/yd_webapp/booking.html
{% extends 'yd_webapp/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
    Booking
{% endblock %}

{% block body_block %}

<form action="{% url 'yd_webapp:booking' %}" method="post">
  {% csrf_token %}
    <div>
    <h3>
        Your Appointment:
    </h3>
            {% for a in appointment %}
                <h4>
                    {{ a.t_id.doctor_id.doctor_name }}
                    {{ a.t_id.get_time_id_display }}
                </h4>
            {% endfor %}
    </div>

    <div class="container">
    <div class="card-group" >
    {% for choice in time_choices %}
        <div>
        <div class="card bg" >
            <div class="card-body text-center">
                <h5 class="card-title"> Dr. {{choice.doctor_id.doctor_name}}
                <div>
                  <p><input type="radio" name="availabletime" value={{ choice.t_id }}> {{ choice.get_time_id_display }}</p>
                </div>
                </h5>
            </div>
        </div>
        </div>

    {% endfor %}
    </div>
    </div>
    <br>
    <div class="text-center">
    <button class="submit-booking" type="submit">Submit</button>
    </div>
</form>
<div class="text-center" >
     <a href="/yd_webapp/patient/">Back to the homepage</a>
    </div>
{% endblock %}

yourdoctor/templates/yd_webapp/doclogin.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "login.css" %}">
    <title>login</title>
</head>
<body>
<div class="text-center">
     <div style="margin: 15% 40%;">
        <h1>login Yourdoctor</h1>
        <h3 class="logindoctor" >login as a Doctor</h3>
       <form action="" method="post">{% csrf_token %}
            {{Error}}
            <p>
                <label for="id_username">Email：</label>
                <input type="text" id="id_username" name="email" placeholder="username" autofocus required />
            </p>
          
            <p>
                <label for="id_password">Password：</label>
                <input type="password" id="id_password" placeholder="password" name="password" required >
            </p>
            <button type="submit" >submit</button>
           <br/>
           <li><a href="/yd_webapp/" role="button">Homepage</a></li>
        </form>
    </div>
    </div>
    <script src="{% static "js1/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>

yourdoctor/templates/yd_webapp/doctoranswer.html
{% extends 'yd_webapp/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
    Online Doctor
{% endblock %}

{% if messages %}
<script>
    {% for msg in messages %}
        alert('{{msg.message}}');
    {% endfor %}
</script>
{% endif %}

{% block body_block %}
<form action='/yd_webapp/onlinedoctor/' method="POST">
 {% csrf_token %}

<div class="accordion text-center" id="accordionExample">
{% for q in questions%}
    <div class="accordion-item">
        <h5 class="accordion-header" id="headingOne">
            Question {{ q.record_id }}: from Patient {{ q.patient_id.patient_name }}
        </h5>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
              {{ q.question_context }}
          </div>
        </div>
    <br/>
      </div>
{% endfor %}
</div>

<br/><br/><br/>
<div class="text-center">
<form class="form-inline" role="form" action='/yd_webapp/onlinedoctor/' method="POST">
 {% csrf_token %}
    <div>
    <h3>
        Answer Questions:
    </h3>
    Please input the Question Number that your will reply to:
    <!--textarea class="form-control" rows="5" id="comment" name="question_id"></textarea-->
    <input type="text" class="input-id" name='question_id' id="inputid" placeholder="">
    <br/><br/><br/>
    <h5> answer this question here:</h5>
    <textarea class="textarea" rows="5" id="inputanswer" name="answer" placeholder="Your answer"></textarea>
    <!--input type="text" class="input-answer" name='answer' id="inputanswer" placeholder="Your answer"-->
    <br/><br/><br/>
<button type="submit">Submit</button>
</div>
</form>
<br/>
<li><a href="/yd_webapp/doctor">Back to the HomePage</a></li>
</div>
{% endblock %}

yourdoctor/templates/yd_webapp/edittime.html
{% extends 'yd_webapp/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
    Doctor
{% endblock %}

{% block body_block %}

<form class="text-center" action='/yd_webapp/edittime/' method="POST">
    {% csrf_token %}

    <div class="form-check">
      <input class="form-check-input" type="checkbox" value=1 id="b1" name="time">
      <label class="form-check-label" for="MonMoring">Monday</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value=2 id="b2" name="time">
      <label class="form-check-label" for="TurMoring">Tuesday</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value=3 id="b3" name="time">
      <label class="form-check-label" for="WedMoring">Wednesday</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value=4 id="b4" name="time">
      <label class="form-check-label" for="MonMoring">Thursday</label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value=5 id="b5" name="time">
      <label class="form-check-label" for="FriMoring">Friday</label>
    </div>

    <button type="submit">Submit</button>
    </form>



<div class="text-center">
    <div>
        <h4 class="some-space">SELECTED TIME</h4>
    {% if timetable %}
        <ul>
        {% for time in timetable%}
        <h5 class="selected-time">{{ time }}</h5>
        {% endfor %}
        </ul>
    {% else %}
        <strong>NO TIME SELECTED</strong>
    {% endif %}
    </div>

     <a class="link button" href="/yd_webapp/doctor">Back to the HomePage</a>
</div>

{% endblock %}

yourdoctor/templates/yd_webapp/index.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'icon/hospital.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "homepage.css" %}">

    <title>
        YourDoctor - Homepage
    </title>
  </head>
<body>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1>YourDoctor</h1>      
          <p>Sign in to book and ask.</p>
        </div>
      </div>

<div class="text-center">
{% if request.session.is_login %}
    <h1>Welcome！ {{ request.session.username }}! </h1>
    <a class="link button" href="/yd_webapp/patient/">To the user Account</a>
    <a class="link button" href="{% url 'yd_webapp:logout' %}">logout</a>
    
{% else %}
    <a class="link button" href="{% url 'yd_webapp:login' %}">Patient Login</a>
    <a class="link button" href="{% url 'yd_webapp:doclogin' %}">Doctor Login</a>
    <a class="link button" href="{% url 'yd_webapp:register' %}">Sign up</a>

{% endif %}
    <script src="{% static "js1/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
</div>
</body>
</html>

yourdoctor/templates/yd_webapp/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "login.css" %}">
    <title>login</title>
    
</head>
<body>
    {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{msg.message}}');
            {% endfor %}
        </script>
    {% endif %}
     <div style="margin: 15% 40%;">
        <h1>Welcome to YourDoctor!</h1>
        <h3 class="loginpatient">Login as a Patient</h3>
       <form action="" method="post">{% csrf_token %}
            {{Error}}
            <p>
                <label for="id_username">Email：</label>
                <input type="text" id="id_username" name="email" placeholder="username" autofocus required />
            </p>

            <p>
                <label for="id_password">Password：</label>
                <input type="password" id="id_password" placeholder="password" name="password" required >
            </p>
            <button type="submit" >Log In</button>


            <h6> A new patient? Don't worry! Register to our website. </h6>
            <li><a href="/yd_webapp/register">Register Now</a></li>
            <li><a href="/yd_webapp/" role="button">Homepage</a></li>

        </form>
    </div>
    <script src="{% static "js1/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>

yourdoctor/templates/yd_webapp/patient.html
{% extends 'yd_webapp/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
    Account
{% endblock %}

{% block body_block %}

     {% if messages %}
        <script>
            {% for msg in messages %}
                alert('{{msg.message}}');
            {% endfor %}
        </script>
    {% endif %}

<div class="row">
<div class="column side">
  <h2>Account</h2>
  {% if request.session.is_login %}
<div class="card" style="width: 18rem;">
    <img src="{% static 'icon/user.png' %}" class="card-img-top" alt="icon of hospital">
    <div class="card-body">
      <h5 class="card-title">Name: {{ request.session.user_name }}
      <h5 class="card-title">Gender: {{ request.session.user_gender }}
      <h5 class="card-title">Age: {{ request.session.user_age }}
      <h5 class="card-title">Address: {{ request.session.user_address }}
      <h5 class="card-title">Phone: {{ request.session.user_phone }}

      <br/><br/><a href="{% url 'yd_webapp:logout' %}" class="btn btn-primary">Logout</a>
      
    </div>
    {% else %}
    <a href="{% url 'yd_webapp:login' %}">login</a>
    <a href="{% url 'yd_webapp:register' %}">sign up</a>
    {% endif %}
  </div>
</div>

<div class="column body">
  <h2>Functions</h2>
    <a href="{% url 'yd_webapp:booking' %}" class="link button">Appointment</a>
    <a href="{% url 'yd_webapp:message' %}" class="link button">Message</a>
    <a href="/yd_webapp/feedback_page/" class="link button disabled" role="button" aria-disabled="true">Feedback</a>
</div>

</div>
{% endblock %}

yourdoctor/templates/yd_webapp/questions.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    
    <title>online_docter</title>
    
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>

<div >


<form action='/yd_webapp/message/' method="POST">
    
     {% csrf_token %}
<div>
    <div style="width: 400px;height:120px;font-size: 40px;line-height: 120px;text-align: center;border: 2px solid black;margin-left: 40px;margin-top: 70px;">Message</div>
    <div style="width: 300px;height:200px;position: fixed;top: 30%;left: 0;right: 0;margin: 0 auto;">
        <table>
            <tr>
                <td>Your Email:</td>
                <td><input id="pid" name="email" style="width:450px;" type="text" ></td>
            </tr>
            <tr>
                <td>Question:</td>
                <td><textarea id="p-question" name="question" cols="60" rows="10"></textarea></td>
            </tr>
            <tr>
                <td></td>
                <td><button id="pq-btn" style="width: 200px;height: 40px;font-size: 25px;">Submit</button></td>
            </tr>
        </table>
        <a href="/yd_webapp/patient/">Back to the homepage</a>
    </div>
</div>
</div>
</form>

</body>
<script>
    $("#pq-btn").click(function () {
        $.ajax({
            url:'/save_question_patient/',
            type:'post',
            dataType:'json',
            data:{
                pid:$("#pid").val(),
                question:$("#p-question").val(),
            },
            success:function (res) {
                alert(res.data);
                window.location.reload();
            }
        })
    })
</script>
</html>

yourdoctor/templates/yd_webapp/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>register</title>
</head>
<body>
    <div class="text-center">
     <div style="margin: 15% 20%;">
        <h1>Create your Account</h1>
        <form action="" method="post">
            {% csrf_token %}

            <p>Email:<br/><input type="text" id="id_username" name="email" placeholder="email" autofocus required /></p>
            <p>Username:<br/><input type="text" id="id_username" name="username" placeholder="username" autofocus required /></p>
            <p>Age:<br/><input type="text" id="id_username" name="age" placeholder="age" autofocus required /></p>

{#            <p>Gender:<br/><input type="text" id="id_username" name="gender" placeholder="gender" autofocus required /></p>#}
            <p>Gender:<br/>
            <select name="gender">
                <option>Female</option>
                <option>Male</option>
                <option>Others</option>
            </select>

            <p>Phone Number:<br/><input type="text" id="id_username" name="phonenumber" placeholder="phonenumber" autofocus required /></p>
            <p>Address:<br/><input type="text" id="id_username" name="address" placeholder="address" autofocus required /></p>

            <p>Password:<br/><input type="text" id="id_username" name="password" placeholder="password" autofocus required /></p>
            <p>Comfirm your password:<br/><input type="text" id="id_username" name="confirm_pwd" placeholder="password" autofocus required /></p>

            <button type="submit" >Confirm</button>
            <br/>
        </form>

         {% if error_message %}
            <p id="error">*{{error_message}}</p>
         {% endif %}

         <br/>
         <li><a href="/yd_webapp/login">Back to the HomePage</a></li>

    </div>
    </div>
    <script src="{% static "js1/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

yourdoctor/templates/yd_webapp/user.html
{% extends 'yd_webapp/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
    Account
{% endblock %}

{% block body_block %}

<div class="card" style="width: 18rem;">
    <img src="{% static 'icon/hospital.png' %}" class="card-img-top" alt="icon of hospital">
    <div class="card-body">
      <h5 class="card-title"> user Name
          <div><!--
            {% if user.is_authenticated %}
            {{user.user.name}}
            {% else %}
            hey there partner
            {%endif%}
          </div>-->
        </h5>
      <p class="card-text">在这里显示用户介绍，属于account内容？</p>
      <a href="#" class="btn btn-pill btn-success">前往编辑个人信息</a>
<!--另一个问题是将变化的超链放入该处a tag，理论可行，但是得先完成url的设置-->
    </div>
  </div>
{% endblock %}